#!/usr/bin/env node
// Convert a snarkjs verification_key.json into the Rust Groth16Verifyingkey
// literal embedded at programs/ayni/src/verifying_key.rs.
//
//   node scripts/vk_to_rust.js build/verification_key.json > programs/ayni/src/verifying_key.rs
//
// Encoding conventions match app/lineage/prove.ts and groth16-solana:
//   - G1 points: x||y, each 32-byte big-endian (64 bytes).
//   - G2 points: per coordinate, Fp2 ordered c1||c0; (x.c1,x.c0,y.c1,y.c0) (128 bytes).
// Verify against the installed groth16-solana version before trusting it.

const fs = require("fs");

const path = process.argv[2];
if (!path) {
  console.error("usage: node scripts/vk_to_rust.js <verification_key.json>");
  process.exit(1);
}
const vk = JSON.parse(fs.readFileSync(path, "utf8"));

function be32(x) {
  let v = BigInt(x);
  const out = [];
  for (let i = 31; i >= 0; i--) {
    out[i] = Number(v & 0xffn);
    v >>= 8n;
  }
  return out;
}
const g1 = (p) => [...be32(p[0]), ...be32(p[1])];
const g2 = (p) => [
  ...be32(p[0][1]), ...be32(p[0][0]),
  ...be32(p[1][1]), ...be32(p[1][0]),
];
const arr = (bytes) => `[${bytes.join("u8, ")}u8]`;

const ic = vk.IC.map((p) => `        ${arr(g1(p))},`).join("\n");

process.stdout.write(`// AUTO-GENERATED by scripts/vk_to_rust.js — do not edit by hand.
use groth16_solana::groth16::Groth16Verifyingkey;

pub const VERIFYING_KEY: Groth16Verifyingkey = Groth16Verifyingkey {
    nr_pubinputs: ${vk.nPublic},
    vk_alpha_g1: ${arr(g1(vk.vk_alpha_1))},
    vk_beta_g2: ${arr(g2(vk.vk_beta_2))},
    vk_gamme_g2: ${arr(g2(vk.vk_gamma_2))},
    vk_delta_g2: ${arr(g2(vk.vk_delta_2))},
    vk_ic: &[
${ic}
    ],
};
`);
