"use client";

// The Glossary — a browsable, searchable reference for the vocabulary the
// fellowship's material draws on (Rosecroix, Shamanism, Alchemy, Numerology,
// the Andean and Celtic strands...), each term cross-tagged to the Twelve Steps.
//
// Data: /glossary.json, generated by scripts/build-glossary.mjs from
// glossary/glossary_v1.xlsx (the human-editable source of record). Fetched at
// runtime rather than imported, so 167 KB of reference text never enters the JS
// bundle of every other page.
//
// PRIVACY: this page reads a static file and nothing else. No chain call, no
// wallet, no member data, no analytics — a visitor may read the whole glossary
// without connecting anything, and nothing here records that they did. Any
// future "recently viewed" or similar must stay in local state only.

import { useEffect, useMemo, useRef, useState } from "react";
import { useT } from "../../components/SettingsProvider";

type Entry = { word: string; explanation: string; tags: string[]; related: string[] };
type Payload = { count: number; legend: Record<string, string>; entries: Entry[] };

/** "Step 7" -> 7, anything else -> null. */
function stepOf(tag: string): number | null {
  const m = /^Step\s+(\d{1,2})$/i.exec(tag.trim());
  if (!m) return null;
  const n = Number(m[1]);
  return n >= 1 && n <= 12 ? n : null;
}

/** Tradition/origin tags are everything that is not a Step and not Numerology's
 *  companion "Origin: ..." duplicate — we keep "Origin: X" as the canonical
 *  tradition and drop the bare duplicate only when both are present. */
function traditionsOf(tags: string[]): string[] {
  return tags.filter((t) => stepOf(t) === null);
}

const norm = (s: string) => s.toLowerCase().normalize("NFKD").replace(/[̀-ͯ]/g, "");

/** Case/accent-insensitive highlight of every match of `q` in `text`. */
function Highlight({ text, q }: { text: string; q: string }) {
  if (!q.trim()) return <>{text}</>;
  const hay = norm(text);
  const needle = norm(q.trim());
  const parts: React.ReactNode[] = [];
  let i = 0;
  let n = 0;
  for (;;) {
    const at = hay.indexOf(needle, i);
    if (at < 0 || needle.length === 0) break;
    if (at > i) parts.push(text.slice(i, at));
    parts.push(<mark key={n++}>{text.slice(at, at + needle.length)}</mark>);
    i = at + needle.length;
  }
  parts.push(text.slice(i));
  return <>{parts}</>;
}

const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ".split("");

/** First letter used for the A–Z index; entries starting with a digit group
 *  under "#" (the Sacred Numbers run from "1 — One" upward). */
function initialOf(word: string): string {
  const c = norm(word).replace(/^[^a-z0-9]+/, "").charAt(0).toUpperCase();
  if (!c) return "#";
  return /[0-9]/.test(c) ? "#" : c;
}

export default function GlossaryPage() {
  const t = useT();
  const [data, setData] = useState<Payload | null>(null);
  const [failed, setFailed] = useState(false);
  const [q, setQ] = useState("");
  const [step, setStep] = useState<number | null>(null);
  const [tradition, setTradition] = useState<string | null>(null);
  const [letter, setLetter] = useState<string | null>(null);
  const searchRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    fetch("/glossary.json")
      .then((r) => (r.ok ? r.json() : Promise.reject(new Error(String(r.status)))))
      .then(setData)
      .catch(() => setFailed(true));
  }, []);

  // Deep links: /glossary?q=alchemy — read once on mount so a shared link lands
  // on the right search without fighting the user's later typing.
  useEffect(() => {
    const p = new URLSearchParams(window.location.search).get("q");
    if (p) setQ(p);
  }, []);

  const entries = data?.entries ?? [];

  const traditions = useMemo(() => {
    const counts = new Map<string, number>();
    for (const e of entries) for (const tr of traditionsOf(e.tags)) counts.set(tr, (counts.get(tr) ?? 0) + 1);
    return [...counts.entries()].sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]));
  }, [entries]);

  const stepCounts = useMemo(() => {
    const counts = new Map<number, number>();
    for (const e of entries) for (const tag of e.tags) {
      const s = stepOf(tag);
      if (s) counts.set(s, (counts.get(s) ?? 0) + 1);
    }
    return counts;
  }, [entries]);

  const shown = useMemo(() => {
    const needle = norm(q.trim());
    return entries.filter((e) => {
      if (step !== null && !e.tags.some((tg) => stepOf(tg) === step)) return false;
      if (tradition && !e.tags.includes(tradition)) return false;
      if (letter && initialOf(e.word) !== letter) return false;
      if (!needle) return true;
      return (
        norm(e.word).includes(needle) ||
        norm(e.explanation).includes(needle) ||
        e.tags.some((tg) => norm(tg).includes(needle))
      );
    });
  }, [entries, q, step, tradition, letter]);

  // Which A–Z buckets actually contain something, so dead letters look dead.
  const liveLetters = useMemo(() => {
    const s = new Set<string>();
    for (const e of entries) s.add(initialOf(e.word));
    return s;
  }, [entries]);

  const filtering = q.trim() !== "" || step !== null || tradition !== null || letter !== null;
  const clearAll = () => { setQ(""); setStep(null); setTradition(null); setLetter(null); searchRef.current?.focus(); };

  /** Clicking a "related to" chip searches for that term. */
  const lookUp = (term: string) => {
    setStep(null); setTradition(null); setLetter(null);
    setQ(term);
    window.scrollTo({ top: 0, behavior: "smooth" });
  };

  return (
    <>
      <h1 style={{ marginBottom: 4 }}>{t("glossary.title")}</h1>
      <p className="lede" style={{ marginTop: 0 }}>{t("glossary.lede")}</p>

      {failed && <div className="card"><p className="muted" style={{ margin: 0 }}>{t("glossary.failed")}</p></div>}
      {!data && !failed && <div className="card"><p className="muted" style={{ margin: 0 }}>{t("glossary.loading")}</p></div>}

      {data && (
        <>
          <div className="card" style={{ position: "sticky", top: 8, zIndex: 5 }}>
            <div className="form-row col">
              <label htmlFor="glossary-q">{t("glossary.searchLabel")}</label>
              <input
                id="glossary-q"
                ref={searchRef}
                type="search"
                value={q}
                onChange={(e) => setQ(e.target.value)}
                placeholder={t("glossary.searchPlaceholder")}
                autoComplete="off"
              />
            </div>

            {/* Steps 1–12 */}
            <div style={{ marginTop: 10 }}>
              <div className="muted sm" style={{ marginBottom: 4 }}>{t("glossary.byStep")}</div>
              <div className="row" style={{ flexWrap: "wrap", gap: 6 }}>
                {Array.from({ length: 12 }, (_, i) => i + 1).map((n) => (
                  <button
                    key={n}
                    type="button"
                    className={`pill${step === n ? " is-on" : ""}`}
                    aria-pressed={step === n}
                    onClick={() => setStep(step === n ? null : n)}
                    disabled={!stepCounts.get(n)}
                    title={`${stepCounts.get(n) ?? 0}`}
                  >
                    {n}
                  </button>
                ))}
              </div>
            </div>

            {/* Traditions, most-populated first */}
            <div style={{ marginTop: 10 }}>
              <div className="muted sm" style={{ marginBottom: 4 }}>{t("glossary.byTradition")}</div>
              <div className="row" style={{ flexWrap: "wrap", gap: 6 }}>
                {traditions.map(([name, n]) => (
                  <button
                    key={name}
                    type="button"
                    className={`pill${tradition === name ? " is-on" : ""}`}
                    aria-pressed={tradition === name}
                    onClick={() => setTradition(tradition === name ? null : name)}
                  >
                    {name.replace(/^Origin:\s*/, "")} <span className="muted">{n}</span>
                  </button>
                ))}
              </div>
            </div>

            {/* A–Z */}
            <div style={{ marginTop: 10 }}>
              <div className="muted sm" style={{ marginBottom: 4 }}>{t("glossary.byLetter")}</div>
              <div className="row" style={{ flexWrap: "wrap", gap: 4 }}>
                {["#", ...ALPHABET].map((c) => (
                  <button
                    key={c}
                    type="button"
                    className={`pill${letter === c ? " is-on" : ""}`}
                    aria-pressed={letter === c}
                    disabled={!liveLetters.has(c)}
                    onClick={() => setLetter(letter === c ? null : c)}
                  >
                    {c}
                  </button>
                ))}
              </div>
            </div>

            <div className="row" style={{ justifyContent: "space-between", alignItems: "center", marginTop: 10 }}>
              <span className="muted sm">
                {shown.length} / {data.count} {t("glossary.terms")}
              </span>
              {filtering && (
                <button type="button" className="pill" onClick={clearAll}>{t("glossary.clear")}</button>
              )}
            </div>
          </div>

          {shown.length === 0 && (
            <div className="card">
              <p style={{ margin: 0 }}>{t("glossary.noResults")}</p>
              <p className="muted sm" style={{ marginBottom: 0 }}>{t("glossary.noResultsHint")}</p>
            </div>
          )}

          <div className="grid" style={{ gap: 12, marginTop: 12 }}>
            {shown.map((e) => (
              <article className="card" key={e.word} id={`t-${encodeURIComponent(e.word)}`}>
                <h2 style={{ fontSize: 18, margin: "0 0 6px" }}>
                  <Highlight text={e.word} q={q} />
                </h2>
                {e.tags.length > 0 && (
                  <div className="row" style={{ flexWrap: "wrap", gap: 6, marginBottom: 8 }}>
                    {e.tags.map((tg) => {
                      const s = stepOf(tg);
                      return (
                        <button
                          key={tg}
                          type="button"
                          className="pill"
                          onClick={() => (s ? setStep(s) : setTradition(tg))}
                          title={data.legend[tg] || undefined}
                        >
                          {tg.replace(/^Origin:\s*/, "")}
                        </button>
                      );
                    })}
                  </div>
                )}
                <p style={{ margin: 0 }}>
                  <Highlight text={e.explanation} q={q} />
                </p>
                {e.related.length > 0 && (
                  <p className="muted sm" style={{ margin: "8px 0 0" }}>
                    {t("glossary.relatedTo")}{" "}
                    {e.related.map((r, i) => (
                      <span key={r}>
                        {i > 0 && " · "}
                        <button type="button" className="linklike" onClick={() => lookUp(r)}>{r}</button>
                      </span>
                    ))}
                  </p>
                )}
              </article>
            ))}
          </div>

          <p className="muted sm" style={{ marginTop: 16 }}>{t("glossary.sourceNote")}</p>
        </>
      )}
    </>
  );
}
